#!/bin/bash
mpirun -np 16 -host n03,n05,n06,n07 ./bin/cg.C.16_baseline | tee finalresult/cf_c_16_1_32bw_baseline.log
mpirun -np 16 -host n03,n05,n06,n07 ./bin/cg.C.16_memcpy | tee finalresult/cg_c_16_1_32bw_memcpy.log
mpirun -np 16 -host n03,n05,n06,n07 ./bin/cg.C.16_sse2 | tee finalresult/cg_c_16_1_32bw_sse2.log
mpirun -np 16 -host n03,n05,n06,n07 ./bin/cg.C.16_memcpy_openmp | tee finalresult/cg_c_16_1_32bw_memcpy_openmp.log
mpirun -np 16 -host n03,n05,n06,n07 ./bin/cg.C.16_sse2_openmp | tee finalresult/cg_c_16_1_32bw_sse2_openmp.log
mpirun -np 16 -host n03,n05,n06,n07 ./bin/cg.C.16_memcpy_openmp2 | tee finalresult/cg_c_16_1_32bw_memcpy_openmp2.log
